name: DSA test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt update && sudo apt install -y build-essential valgrind libncurses-dev clang-format

      - name: Format the code
        run: make fmt

      - name: Check formatting
        run: git diff --exit-code
        
      - name: Run tests
        run: make test

      - name: Memory check with valgrind
        run: make valgrind

  sanitizers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt update && sudo apt install -y build-essential libncurses-dev

      - name: Build and test with AddressSanitizer + UBSan
        run: make asan
