name: DSA test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt update && sudo apt install -y build-essential cmake valgrind libncurses-dev clang-format

      - name: Configure project
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build --parallel

      - name: Format the code
        run: cmake --build build --target fmt

      - name: Check formatting
        run: git diff --exit-code
        
      - name: Run tests
        run: ctest --test-dir build --output-on-failure --verbose

      - name: Memory check with valgrind
        run: cmake --build build --target valgrind

      - name: Configure ASan build
        run: cmake -S . -B build-asan -DSANITIZE=ON
      
      - name: Build ASan
        run: cmake --build build-asan --parallel
      
      - name: Run ASan tests
        run: ctest --test-dir build-asan --output-on-failure --verbose
